services:
  web:
    build: .
    command: bash -c "until pg_isready -h db -p 5432; do sleep 2; done && rails s -b 0.0.0.0"
    volumes:
      - ruby-2.7.2-gems:/usr/local/bundle
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: yourpassword

volumes:
  ruby-2.7.2-gems:
    external: true
  db-data: